# Generated by Django 4.1.7 on 2023-04-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='McheyneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('part1', models.CharField(max_length=30)),
                ('part2', models.CharField(max_length=30)),
                ('part3', models.CharField(max_length=30)),
                ('part4', models.CharField(max_length=30)),
                ('part1_start_book', models.CharField(max_length=3)),
                ('part1_start_chapter', models.PositiveIntegerField()),
                ('part1_start_verse', models.PositiveIntegerField()),
                ('part1_end_book', models.CharField(max_length=3)),
                ('part1_end_chapter', models.PositiveIntegerField()),
                ('part1_end_verse', models.PositiveIntegerField()),
                ('part2_start_book', models.CharField(max_length=3)),
                ('part2_start_chapter', models.PositiveIntegerField()),
                ('part2_start_verse', models.PositiveIntegerField()),
                ('part2_end_book', models.CharField(max_length=3)),
                ('part2_end_chapter', models.PositiveIntegerField()),
                ('part2_end_verse', models.PositiveIntegerField()),
                ('part3_start_book', models.CharField(max_length=3)),
                ('part3_start_chapter', models.PositiveIntegerField()),
                ('part3_start_verse', models.PositiveIntegerField()),
                ('part3_end_book', models.CharField(max_length=3)),
                ('part3_end_chapter', models.PositiveIntegerField()),
                ('part3_end_verse', models.PositiveIntegerField()),
                ('part4_start_book', models.CharField(max_length=3)),
                ('part4_start_chapter', models.PositiveIntegerField()),
                ('part4_start_verse', models.PositiveIntegerField()),
                ('part4_end_book', models.CharField(max_length=3)),
                ('part4_end_chapter', models.PositiveIntegerField()),
                ('part4_end_verse', models.PositiveIntegerField()),
            ],
        ),
    ]
