# Generated by Django 4.1.7 on 2023-04-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bible", "0002_mcheynemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="BibleMetaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book", models.CharField(max_length=3)),
                ("full_name", models.CharField(max_length=15)),
                ("chap_num", models.PositiveSmallIntegerField()),
                ("testament", models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name="Abbreviation",
        ),
    ]
