# Generated by Django 4.1.7 on 2023-04-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bible", "0003_biblemetamodel_delete_abbreviation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="biblemetamodel",
            old_name="chap_num",
            new_name="chapter_length",
        ),
        migrations.AddField(
            model_name="biblemetamodel",
            name="verse_length",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
